php:
  build: .
  ports:
  - "${PHP_PORT}:80"
  - "443:443"
  volumes:
  - ./:/var/www/html
  env_file: .env
  links:
  - db

db:
  image: mysql:5.7
  volumes:
  - /var/lib/mysql
  environment:
  - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PWD}
  - MYSQL_DATABASE=${MYSQL_DB}
  env_file: .env